version: '3.7'
services:
  database:
    build:
      context: ./database
      dockerfile: database.dockerfile
    volumes:
      - dbdata:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"

  builder:
    container_name: builder
    build:
      context: ./../rest_api/crmProject
      dockerfile: appbuilder.dockerfile

  runtime:
    container_name: runtime
    build:
      context: ./../rest_api/crmProject
      dockerfile: runtime_app.dockerfile
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - 8080:8080
      - 5006:5005

volumes:
  dbdata:
